# Generated by Django 3.2.9 on 2022-01-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
