# Generated by Django 3.2.9 on 2022-01-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=500, null=True),
        ),
    ]
